spring:
  redis:
    host: 192.168.112.130
    port: 6379
    password: kingredis
    timeout: 2000

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: jdbc:mysql://192.168.137.129:3306/candao?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
        username: root
        password: woshimima
      salve:
        enabled: false
        url: jdbc:mysql://192.168.137.129:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
        username: root
        password: woshimima
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 50000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: select 1 from dual
      validation-query-timeout: 20000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 600000
      min-evictable-idle-time-millis: 300000

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
